blank_issues_enabled: false
contact_links:
  - name: Questions / Discussion
    url: https://github.com/sherwinspinto/personal-finance-tracker/discussions
    about: Use Discussions for questions instead of issues.

